// <auto-generated />
using Coopera.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Coopera.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Coopera.Models.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartidaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("Coopera.Models.JugadorPartida", b =>
                {
                    b.Property<int>("JugadorId")
                        .HasColumnType("int");

                    b.Property<int>("PartidaId")
                        .HasColumnType("int");

                    b.Property<int>("ComidaJugador")
                        .HasColumnType("int");

                    b.Property<int>("MaderaJugador")
                        .HasColumnType("int");

                    b.Property<int>("PiedraJugador")
                        .HasColumnType("int");

                    b.HasKey("JugadorId", "PartidaId");

                    b.HasIndex("PartidaId");

                    b.ToTable("JugadoresPartidas");
                });

            modelBuilder.Entity("Coopera.Models.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Comida")
                        .HasColumnType("int");

                    b.Property<int>("Dificultad")
                        .HasColumnType("int");

                    b.Property<int>("Madera")
                        .HasColumnType("int");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<int>("Piedra")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("Coopera.Models.Jugador", b =>
                {
                    b.HasOne("Coopera.Models.Partida", "Partida")
                        .WithMany()
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("Coopera.Models.JugadorPartida", b =>
                {
                    b.HasOne("Coopera.Models.Jugador", "Jugador")
                        .WithMany("JugadorPartidas")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coopera.Models.Partida", "Partida")
                        .WithMany("PartidaJugadores")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Jugador");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("Coopera.Models.Jugador", b =>
                {
                    b.Navigation("JugadorPartidas");
                });

            modelBuilder.Entity("Coopera.Models.Partida", b =>
                {
                    b.Navigation("PartidaJugadores");
                });
#pragma warning restore 612, 618
        }
    }
}
