// <auto-generated />
using System;
using Coopera.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Coopera.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Coopera.Models.Jugador", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Jugadores", (string)null);
                });

            modelBuilder.Entity("Coopera.Models.JugadorPartida", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("JugadorID")
                        .HasColumnType("int");

                    b.Property<int>("PartidaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("JugadorID");

                    b.HasIndex("PartidaID");

                    b.ToTable("Jugadores_Partidas", (string)null);
                });

            modelBuilder.Entity("Coopera.Models.Partida", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("MetaComida")
                        .HasColumnType("int");

                    b.Property<int>("MetaMadera")
                        .HasColumnType("int");

                    b.Property<int>("MetaPiedra")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Partidas", (string)null);
                });

            modelBuilder.Entity("Coopera.Models.Recurso", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Recursos", (string)null);
                });

            modelBuilder.Entity("Coopera.Models.RegistroRecursos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("PartidaID")
                        .HasColumnType("int");

                    b.Property<int>("RecursoID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PartidaID");

                    b.HasIndex("RecursoID");

                    b.ToTable("Registros_Recursos", (string)null);
                });

            modelBuilder.Entity("Coopera.Models.JugadorPartida", b =>
                {
                    b.HasOne("Coopera.Models.Jugador", "Jugador")
                        .WithMany("PartidasJugadas")
                        .HasForeignKey("JugadorID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Coopera.Models.Partida", "Partida")
                        .WithMany("JugadoresPartidas")
                        .HasForeignKey("PartidaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugador");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("Coopera.Models.RegistroRecursos", b =>
                {
                    b.HasOne("Coopera.Models.Partida", "Partida")
                        .WithMany("RegistroIngresos")
                        .HasForeignKey("PartidaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coopera.Models.Recurso", "Recurso")
                        .WithMany("Registros")
                        .HasForeignKey("RecursoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("Coopera.Models.Jugador", b =>
                {
                    b.Navigation("PartidasJugadas");
                });

            modelBuilder.Entity("Coopera.Models.Partida", b =>
                {
                    b.Navigation("JugadoresPartidas");

                    b.Navigation("RegistroIngresos");
                });

            modelBuilder.Entity("Coopera.Models.Recurso", b =>
                {
                    b.Navigation("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
